[data]
sky_model = fits_file_name
fits_mask = None  # Just file name, not path
override = True
ms_dir = synthms
# MS = ../ms/L689778_SB151_uv.pre-cal_12D05945Ft_152MHz.pre-cal.MS

[control]
synthms = False  # Make a synthetic LoTSS-pointing-like MS 
predict = True  # Predict visibilities from sky model
losito = True  # Run LoSiTo (default: Noise)
ddf = True  # Run DDF analysis
ClusterCat = False  # Run ClusterCat
ddf-pipeline = False  # Run DDF pipeline

[synthms]
tstart = 2018-11-30 15:14:39.006

[losito]
run_independent = False  
do_predict = False

[ddf]
preset = Hogbom  # Options: SSD, HMP, Hogbom
resume = False

[ClusterCat]
FluxMin = 0.001

[ddf-pipeline]
restart = False
make_ms_sublist = True
Npix = None
ndir = 5
clusterfile = None  # Must be relative to the map directory.